export const studiesEs = [
  {
    id: 1,
    institution: "ACADEMLO",
    date: "2023",
    description: "Fundamentos en HTML, CSS and Javascript",
    img: "./img/logo_academlo.png",
    link: "https://certiwise.co/verify/107",
  },
  {
    id: 2,
    institution: "ACADEMLO",
    date: "2023",
    description: "Desarrollo Back-End con Node.js",
    img: "./img/logo_academlo.png",
    link: "https://certiwise.co/verify/213",
  },
  {
    id: 3,
    institution: "ACADEMLO",
    date: "2023",
    description: "Desarrollo Front-End con React",
    img: "./img/logo_academlo.png",
    link: "https://certiwise.co/verify/357",
  },
  {
    id: 4,
    institution: "CISCO",
    date: "2022",
    description: "Conectarse",
    img: "./img/cisco-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrHuoa0nlCkXY6We-?e=eRyqnn",
  },
  {
    id: 5,
    institution: "LINKEDIN",
    date: "2022",
    description: "SQL Sever 2019 Essential",
    img: "./img/linkedin-logo-240.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrRKRZX1A0WPlLvTK?e=0GTDLn",
  },
  {
    id: 6,
    institution: "UDEMY",
    date: "2022",
    description: "Cisco CCNA 200-301",
    img: "./img/Udemy-Logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQHi52mA9tQw60Ol?e=adItIK",
  },
  {
    id: 7,
    institution: "INFOTEP",
    date: "2021",
    description: "Auxiliar Infraestructura de Redes",
    img: "./img/infotep-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQQnXU8YB8RbaczK?e=Xz9kZf",
  },
  {
    id: 8,
    institution: "UDEMY",
    date: "2021",
    description: "Windows Server 2016",
    img: "./img/Udemy-Logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQVeDtm6mPr-ytCX?e=pwogW9",
  },
  {
    id: 9,
    institution: "CENTU",
    date: "2019",
    description: "Programacion .NET",
    img: "./img/centu-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQehJ2UsUHgCUrpC?e=gUmmzY",
  },
  {
    id: 10,
    institution: "FORTINET",
    date: "2022",
    description: "Network Security Associate",
    img: "./img/fortinet-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrH7PSVXBgsULSv_I?e=M88Wis",
  },
  
];

export const studiesEN = [
  {
    id: 1,
    institution: "ACADEMLO",
    date: "2023",
    description: "Foundations in HTML, CSS and Javascript",
    img: "./img/logo_academlo.png",
    link: "https://certiwise.co/verify/107",
  },
  {
    id: 2,
    institution: "ACADEMLO",
    date: "2023",
    description: "Back-End Development with Node.js",
    img: "./img/logo_academlo.png",
    link: "https://certiwise.co/verify/213",
  },
  {
    id: 3,
    institution: "ACADEMLO",
    date: "2023",
    description: "Front-End Development with React",
    img: "./img/logo_academlo.png",
    link: "https://certiwise.co/verify/357",
  },
  {
    id: 4,
    institution: "CISCO",
    date: "2022",
    description: "Get Connected",
    img: "./img/cisco-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrHuoa0nlCkXY6We-?e=eRyqnn",
  },
  {
    id: 5,
    institution: "LINKEDIN",
    date: "2022",
    description: "SQL Sever 2019 Essential",
    img: "./img/linkedin-logo-240.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrRKRZX1A0WPlLvTK?e=0GTDLn",
  },
  {
    id: 6,
    institution: "UDEMY",
    date: "2022",
    description: "Cisco CCNA 200-301",
    img: "./img/Udemy-Logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQHi52mA9tQw60Ol?e=adItIK",
  },
  {
    id: 7,
    institution: "INFOTEP",
    date: "2021",
    description: "Network Infrastructure Assistant",
    img: "./img/infotep-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQQnXU8YB8RbaczK?e=Xz9kZf",
  },
  {
    id: 8,
    institution: "UDEMY",
    date: "2021",
    description: "Windows Server 2016",
    img: "./img/Udemy-Logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQVeDtm6mPr-ytCX?e=pwogW9",
  },
  {
    id: 9,
    institution: "CENTU",
    date: "2019",
    description: "Programming .NET",
    img: "./img/centu-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrQehJ2UsUHgCUrpC?e=gUmmzY",
  },
  {
    id: 10,
    institution: "FORTINET",
    date: "2022",
    description: "Network Security Associate",
    img: "./img/fortinet-logo.png",
    link: "https://1drv.ms/b/s!As4YN41Hik6VrH7PSVXBgsULSv_I?e=M88Wis",
  },
];
